### ISSUE TITLE
The size of tensor a (4096) must match the size of tensor b (4544) at non-singleton dimension 2

### ISSUE THREAD

**Issue by Vikramank** [WENGSYX/ControlLM#1]
Hi, 
I'm unable to run inference on as per the give code. 
I'm receiving the following error : 
`The size of tensor a (4096) must match the size of tensor b (4544) at non-singleton dimension 2`
Test environment:
`Python 3.10.10`
`Torch == 2.2.1+cu121`
Model used: `meta-llama/Llama-2-7b-chat-hf`

![image](https://github.com/user-attachments/assets/846bea5b-728e-477e-8304-fc50b07b3802)

**Comment by WENGSYX** [comment]
I apologize that I was unable to reproduce the error you encountered when using transformers version 4.44.0. Could you please provide more detailed version information? Additionally, I'd like to confirm that the `path` parameter in `model.load_and_set_activate(load_path=path, layer=20, gamma=1.5)` contains weights specifically from meta-llama/Llama-2-7b-chat-hf, rather than from another model.

**Comment by Vikramank** [comment]
hi, 
The issue is still continuing with transformers version 4.44.0. I'm attaching my jupyter notebook(zip file) for reference.
the path parameter I used is 
```
personal = 'Conscientiousness'
path = './Activate/' + personal

```
the first time I'm running, I create the vectors by running : 
`model.get_and_save_activations(dataset=datasets, save_path=path)`
[ControlLM.zip](https://github.com/user-attachments/files/17655668/ControlLM.zip)

**Comment by Vikramank** [comment]
Regenerating the activation vectors solved the issue! thanks
